#!/usr/bin/env bash

set -euo pipefail

if ! command -v gsettings >/dev/null 2>&1; then
  echo "error: gsettings is not installed or not in PATH" >&2
  exit 1
fi

if ! command -v xdg-mime >/dev/null 2>&1; then
  echo "error: xdg-mime is not installed or not in PATH" >&2
  exit 1
fi

SKIP_BACKUP=false
for arg in "$@"; do
  case "$arg" in
    --no-backup)
      SKIP_BACKUP=true
      ;;
    -h|--help)
      echo "Usage: $0 [--no-backup]"
      echo "  --no-backup   Apply settings without saving a backup snapshot"
      exit 0
      ;;
    *)
      echo "error: unknown option: $arg" >&2
      echo "Try: $0 --help" >&2
      exit 1
      ;;
  esac
done

set_key() {
  local schema="$1"
  local key="$2"
  local value="$3"
  gsettings set "$schema" "$key" "$value"
}

get_key() {
  local schema="$1"
  local key="$2"
  gsettings get "$schema" "$key"
}

save_current_settings() {
  local ts backup_dir backup_file
  ts="$(date +%Y%m%d-%H%M%S)"
  backup_dir="$HOME/.local/state/gnome-setup"
  backup_file="${backup_dir}/backup-${ts}.sh"
  mkdir -p "$backup_dir"

  {
    echo "#!/usr/bin/env bash"
    echo "set -euo pipefail"
    echo
    echo "# Generated by setup-gnome.sh on ${ts}"
    echo "gsettings set org.gnome.desktop.interface gtk-theme $(get_key org.gnome.desktop.interface gtk-theme)"
    echo "gsettings set org.gnome.desktop.interface icon-theme $(get_key org.gnome.desktop.interface icon-theme)"
    echo "gsettings set org.gnome.desktop.interface color-scheme $(get_key org.gnome.desktop.interface color-scheme)"
    echo
    echo "gsettings set org.gnome.shell.extensions.window-list display-all-workspaces $(get_key org.gnome.shell.extensions.window-list display-all-workspaces)"
    echo "gsettings set org.gnome.shell.extensions.window-list embed-previews $(get_key org.gnome.shell.extensions.window-list embed-previews)"
    echo "gsettings set org.gnome.shell.extensions.window-list grouping-mode $(get_key org.gnome.shell.extensions.window-list grouping-mode)"
    echo "gsettings set org.gnome.shell.extensions.window-list show-on-all-monitors $(get_key org.gnome.shell.extensions.window-list show-on-all-monitors)"
    echo
    echo "gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 $(get_key org.gnome.desktop.wm.keybindings switch-to-workspace-1)"
    echo "gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 $(get_key org.gnome.desktop.wm.keybindings switch-to-workspace-2)"
    echo "gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 $(get_key org.gnome.desktop.wm.keybindings switch-to-workspace-3)"
    echo "gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 $(get_key org.gnome.desktop.wm.keybindings switch-to-workspace-4)"
    echo "gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 $(get_key org.gnome.desktop.wm.keybindings move-to-workspace-1)"
    echo "gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 $(get_key org.gnome.desktop.wm.keybindings move-to-workspace-2)"
    echo "gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 $(get_key org.gnome.desktop.wm.keybindings move-to-workspace-3)"
    echo "gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 $(get_key org.gnome.desktop.wm.keybindings move-to-workspace-4)"
    echo "gsettings set org.gnome.desktop.wm.keybindings switch-windows $(get_key org.gnome.desktop.wm.keybindings switch-windows)"
    echo "gsettings set org.gnome.desktop.wm.keybindings switch-applications $(get_key org.gnome.desktop.wm.keybindings switch-applications)"
    echo "gsettings set org.gnome.desktop.wm.keybindings show-desktop $(get_key org.gnome.desktop.wm.keybindings show-desktop)"
    echo
    echo "xdg-mime default $(xdg-mime query default inode/directory) inode/directory"
    echo "xdg-mime default $(xdg-mime query default application/x-gnome-saved-search) application/x-gnome-saved-search"
    echo
    if gsettings list-schemas | grep -qx "org.gnome.shell.extensions.dash-to-panel"; then
      gsettings list-recursively org.gnome.shell.extensions.dash-to-panel 2>/dev/null \
        | sed -E 's#^org\\.gnome\\.shell\\.extensions\\.dash-to-panel[[:space:]]+([^[:space:]]+)[[:space:]]+#\\1=#' \
        | while IFS='=' read -r key value; do
            [[ -n "$key" ]] && echo "gsettings set org.gnome.shell.extensions.dash-to-panel ${key} ${value}"
          done
    fi
  } > "$backup_file"

  chmod +x "$backup_file"
  echo "Saved current settings snapshot to: $backup_file"
}

apply_dash_to_panel_settings() {
  if ! gsettings list-schemas | grep -qx "org.gnome.shell.extensions.dash-to-panel"; then
    echo "Dash-to-Panel schema not found, skipping extension settings."
    return
  fi

  while IFS='=' read -r key value; do
    [[ -z "$key" ]] && continue
    set_key org.gnome.shell.extensions.dash-to-panel "$key" "$value"
  done <<'EOF'
activate-single-window=true
animate-app-switch=true
animate-appicon-hover=false
animate-appicon-hover-animation-convexity={'RIPPLE': 2.0, 'PLANK': 1.0, 'SIMPLE': 0.0}
animate-appicon-hover-animation-duration={'SIMPLE': uint32 160, 'RIPPLE': 130, 'PLANK': 100}
animate-appicon-hover-animation-extent={'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}
animate-appicon-hover-animation-rotation={'SIMPLE': 0, 'RIPPLE': 10, 'PLANK': 0}
animate-appicon-hover-animation-travel={'SIMPLE': 0.29999999999999999, 'RIPPLE': 0.40000000000000002, 'PLANK': 0.0}
animate-appicon-hover-animation-type='RIPPLE'
animate-appicon-hover-animation-zoom={'SIMPLE': 1.0, 'RIPPLE': 1.25, 'PLANK': 2.0}
animate-window-launch=true
app-ctrl-hotkey-1=['<Ctrl><Super>1']
app-ctrl-hotkey-10=['<Ctrl><Super>0']
app-ctrl-hotkey-2=['<Ctrl><Super>2']
app-ctrl-hotkey-3=['<Ctrl><Super>3']
app-ctrl-hotkey-4=['<Ctrl><Super>4']
app-ctrl-hotkey-5=['<Ctrl><Super>5']
app-ctrl-hotkey-6=['<Ctrl><Super>6']
app-ctrl-hotkey-7=['<Ctrl><Super>7']
app-ctrl-hotkey-8=['<Ctrl><Super>8']
app-ctrl-hotkey-9=['<Ctrl><Super>9']
app-ctrl-hotkey-kp-1=['<Ctrl><Super>KP_1']
app-ctrl-hotkey-kp-10=['<Ctrl><Super>KP_0']
app-ctrl-hotkey-kp-2=['<Ctrl><Super>KP_2']
app-ctrl-hotkey-kp-3=['<Ctrl><Super>KP_3']
app-ctrl-hotkey-kp-4=['<Ctrl><Super>KP_4']
app-ctrl-hotkey-kp-5=['<Ctrl><Super>KP_5']
app-ctrl-hotkey-kp-6=['<Ctrl><Super>KP_6']
app-ctrl-hotkey-kp-7=['<Ctrl><Super>KP_7']
app-ctrl-hotkey-kp-8=['<Ctrl><Super>KP_8']
app-ctrl-hotkey-kp-9=['<Ctrl><Super>KP_9']
app-hotkey-1=['<Super>1']
app-hotkey-10=['<Super>0']
app-hotkey-2=['<Super>2']
app-hotkey-3=['<Super>3']
app-hotkey-4=['<Super>4']
app-hotkey-5=['<Super>5']
app-hotkey-6=['<Super>6']
app-hotkey-7=['<Super>7']
app-hotkey-8=['<Super>8']
app-hotkey-9=['<Super>9']
app-hotkey-kp-1=['<Super>KP_1']
app-hotkey-kp-10=['<Super>KP_0']
app-hotkey-kp-2=['<Super>KP_2']
app-hotkey-kp-3=['<Super>KP_3']
app-hotkey-kp-4=['<Super>KP_4']
app-hotkey-kp-5=['<Super>KP_5']
app-hotkey-kp-6=['<Super>KP_6']
app-hotkey-kp-7=['<Super>KP_7']
app-hotkey-kp-8=['<Super>KP_8']
app-hotkey-kp-9=['<Super>KP_9']
app-shift-hotkey-1=['<Shift><Super>1']
app-shift-hotkey-10=['<Shift><Super>0']
app-shift-hotkey-2=['<Shift><Super>2']
app-shift-hotkey-3=['<Shift><Super>3']
app-shift-hotkey-4=['<Shift><Super>4']
app-shift-hotkey-5=['<Shift><Super>5']
app-shift-hotkey-6=['<Shift><Super>6']
app-shift-hotkey-7=['<Shift><Super>7']
app-shift-hotkey-8=['<Shift><Super>8']
app-shift-hotkey-9=['<Shift><Super>9']
app-shift-hotkey-kp-1=['<Shift><Super>KP_1']
app-shift-hotkey-kp-10=['<Shift><Super>KP_0']
app-shift-hotkey-kp-2=['<Shift><Super>KP_2']
app-shift-hotkey-kp-3=['<Shift><Super>KP_3']
app-shift-hotkey-kp-4=['<Shift><Super>KP_4']
app-shift-hotkey-kp-5=['<Shift><Super>KP_5']
app-shift-hotkey-kp-6=['<Shift><Super>KP_6']
app-shift-hotkey-kp-7=['<Shift><Super>KP_7']
app-shift-hotkey-kp-8=['<Shift><Super>KP_8']
app-shift-hotkey-kp-9=['<Shift><Super>KP_9']
appicon-margin=0
appicon-padding=8
appicon-style='NORMAL'
click-action='CYCLE-MIN'
context-menu-entries='\n        [\n          {\n            "title": "Terminal",\n            "cmd": "TERMINALSETTINGS"\n          },\n          {\n            "title": "System monitor",\n            "cmd": "gnome-system-monitor"\n          },\n          {\n            "title": "Files",\n            "cmd": "nautilus"\n          },\n          {\n            "title": "Extensions",\n            "cmd": "gnome-extensions-app"\n          }\n        ]'
customize-click=true
desktop-line-custom-color='rgba(200,200,200,0.2)'
desktop-line-use-custom-color=false
dot-color-1='#5294e2'
dot-color-2='#5294e2'
dot-color-3='#5294e2'
dot-color-4='#5294e2'
dot-color-dominant=false
dot-color-override=false
dot-color-unfocused-1='#77767b'
dot-color-unfocused-2='#77767b'
dot-color-unfocused-3='#77767b'
dot-color-unfocused-4='#77767b'
dot-color-unfocused-different=false
dot-position='BOTTOM'
dot-size=3
dot-style-focused='METRO'
dot-style-unfocused='DASHES'
enter-peek-mode-timeout=500
extension-version=72
focus-highlight=true
focus-highlight-color='#EEEEEE'
focus-highlight-dominant=true
focus-highlight-opacity=25
global-border-radius=0
group-apps=false
group-apps-label-font-color='#dddddd'
group-apps-label-font-color-minimized='#dddddd'
group-apps-label-font-size=14
group-apps-label-font-weight='inherit'
group-apps-label-max-width=160
group-apps-underline-unfocused=false
group-apps-use-fixed-width=true
group-apps-use-launchers=false
hide-overview-on-startup=false
highlight-appicon-hover=true
highlight-appicon-hover-background-color='rgba(238, 238, 236, 0.1)'
highlight-appicon-hover-border-radius=0
highlight-appicon-pressed-background-color='rgba(238, 238, 236, 0.18)'
hot-keys=false
hotkey-prefix-text='Super'
hotkeys-overlay-combo='TEMPORARILY'
intellihide=false
intellihide-animation-time=200
intellihide-behaviour='FOCUSED_WINDOWS'
intellihide-close-delay=400
intellihide-enable-start-delay=2000
intellihide-hide-from-monitor-windows=false
intellihide-hide-from-windows=false
intellihide-key-toggle=['<Super>i']
intellihide-key-toggle-text='<Super>i'
intellihide-only-secondary=false
intellihide-persisted-state=-1
intellihide-pressure-threshold=100
intellihide-pressure-time=1000
intellihide-reveal-delay=0
intellihide-revealed-hover=true
intellihide-revealed-hover-limit-size=false
intellihide-show-in-fullscreen=false
intellihide-show-on-notification=false
intellihide-use-pointer=true
intellihide-use-pointer-limit-size=false
intellihide-use-pressure=true
isolate-monitors=true
isolate-monitors-with-single-panel=false
isolate-workspaces=true
leave-timeout=100
leftbox-padding=-1
leftbox-size=0
middle-click-action='LAUNCH'
minimize-shift=true
multi-monitors=true
overlay-timeout=750
overview-click-to-exit=true
panel-anchors='{"BOE-0x00000000":"MIDDLE"}'
panel-context-menu-commands=@as []
panel-context-menu-titles=@as []
panel-element-positions='{"BOE-0x00000000":[{"element":"showAppsButton","visible":true,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"centered"},{"element":"centerBox","visible":true,"position":"centered"},{"element":"activitiesButton","visible":true,"position":"stackedBR"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"dateMenu","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":true,"position":"stackedBR"}]}'
panel-element-positions-monitors-sync=true
panel-lengths='{"BOE-0x00000000":100}'
panel-position='BOTTOM'
panel-positions='{}'
panel-side-margins=0
panel-side-padding=0
panel-size=48
panel-sizes='{}'
panel-top-bottom-margins=0
panel-top-bottom-padding=0
peek-mode=true
peek-mode-opacity=40
prefs-opened=false
preview-custom-opacity=10
preview-middle-click-close=true
preview-use-custom-opacity=true
primary-monitor=''
progress-show-bar=true
progress-show-count=false
scroll-icon-action='CYCLE_WINDOWS'
scroll-icon-delay=0
scroll-panel-action='SWITCH_WORKSPACE'
scroll-panel-delay=0
scroll-panel-show-ws-popup=true
secondarymenu-contains-appmenu=true
secondarymenu-contains-showdetails=true
shift-click-action='MINIMIZE'
shift-middle-click-action='LAUNCH'
shortcut=['<Super>q']
shortcut-num-keys='BOTH'
shortcut-overlay-on-secondary=false
shortcut-previews=false
shortcut-text='<Super>q'
shortcut-timeout=2000
show-activities-button=false
show-apps-button-context-menu-commands=@as []
show-apps-button-context-menu-titles=@as []
show-apps-icon-file='/usr/share/pixmaps/archlinux-logo.svg'
show-apps-icon-side-padding=8
show-apps-override-escape=true
show-favorites=true
show-favorites-all-monitors=true
show-running-apps=true
show-showdesktop-delay=500
show-showdesktop-hover=true
show-showdesktop-time=300
show-tooltip=true
show-window-previews=true
show-window-previews-timeout=400
showdesktop-button-width=8
status-icon-padding=-1
stockgs-force-hotcorner=false
stockgs-keep-dash=false
stockgs-keep-top-panel=false
stockgs-panelbtn-click-only=true
target-prefs-page=''
taskbar-locked=false
trans-bg-color='#000'
trans-border-custom-color='rgba(200,200,200,0.2)'
trans-border-use-custom-color=false
trans-border-width=1
trans-dynamic-anim-target=0.90000000000000002
trans-dynamic-anim-time=300
trans-dynamic-behavior='ALL_WINDOWS'
trans-dynamic-distance=20
trans-gradient-bottom-color='#000'
trans-gradient-bottom-opacity=1.0
trans-gradient-top-color='#000000'
trans-gradient-top-opacity=0.0
trans-panel-opacity=0.70000000000000007
trans-use-border=false
trans-use-custom-bg=false
trans-use-custom-gradient=false
trans-use-custom-opacity=true
trans-use-dynamic-opacity=true
tray-padding=-1
tray-size=0
window-preview-animation-time=260
window-preview-aspect-ratio-x=16
window-preview-aspect-ratio-y=10
window-preview-custom-icon-size=16
window-preview-fixed-x=true
window-preview-fixed-y=false
window-preview-hide-immediate-click=false
window-preview-manual-styling=false
window-preview-padding=8
window-preview-show-title=false
window-preview-size=240
window-preview-title-font-color='#dddddd'
window-preview-title-font-size=14
window-preview-title-font-weight='inherit'
window-preview-title-position='TOP'
window-preview-use-custom-icon-size=false
EOF
}

set_custom_keybinding() {
  local path="$1"
  local name="$2"
  local command="$3"
  local binding="$4"
  local schema="org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:${path}"

  set_key "$schema" name "'${name}'"
  set_key "$schema" command "'${command}'"
  set_key "$schema" binding "'${binding}'"
}

if [[ "$SKIP_BACKUP" == true ]]; then
  echo "Skipping GNOME settings snapshot (--no-backup)."
else
  echo "Saving current GNOME settings snapshot..."
  save_current_settings
fi

echo "Applying GNOME setup..."

# Theme + dark mode behavior.
set_key org.gnome.desktop.interface gtk-theme "'adw-gtk3-dark'"
set_key org.gnome.desktop.interface icon-theme "'Papirus-Dark'"
set_key org.gnome.desktop.interface color-scheme "'prefer-dark'"

# Workspace navigation and moving windows.
set_key org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>1']"
set_key org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>2']"
set_key org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>3']"
set_key org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>4']"

set_key org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Shift><Super>1']"
set_key org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Shift><Super>2']"
set_key org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Shift><Super>3']"
set_key org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Shift><Super>4']"

# Alt+Tab switches windows directly.
set_key org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab']"
set_key org.gnome.desktop.wm.keybindings switch-applications "@as []"
set_key org.gnome.desktop.wm.keybindings show-desktop "['<Super>d']"

# Remove GNOME's default Super+1..9 app shortcuts so they do not
# conflict with workspace switching.
for i in {1..9}; do
  set_key org.gnome.shell.keybindings "switch-to-application-${i}" "@as []"
done

# Custom launchers.
BASE="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
K0="${BASE}/custom0/"
K1="${BASE}/custom1/"
K2="${BASE}/custom2/"
TERMINAL_LAUNCHER="bash -lc \"term=\$(gsettings get org.gnome.desktop.default-applications.terminal exec | tr -d \\\"\\\\047\\\"); if [ -n \\\"\$term\\\" ] && command -v \\\"\$term\\\" >/dev/null 2>&1; then exec \\\"\$term\\\"; elif command -v kitty >/dev/null 2>&1; then exec kitty; elif command -v gnome-terminal >/dev/null 2>&1; then exec gnome-terminal; else exec xterm; fi\""
set_key org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['${K0}', '${K1}', '${K2}']"
set_custom_keybinding "$K0" "Terminal" "$TERMINAL_LAUNCHER" "<Super>Return"
set_custom_keybinding "$K1" "Files" "nautilus --new-window" "<Super>e"
set_custom_keybinding "$K2" "Terminal (Ctrl+Alt+T)" "$TERMINAL_LAUNCHER" "<Primary><Alt>t"

# Window List extension behavior.
set_key org.gnome.shell.extensions.window-list display-all-workspaces "false"
set_key org.gnome.shell.extensions.window-list embed-previews "true"
set_key org.gnome.shell.extensions.window-list grouping-mode "'never'"
set_key org.gnome.shell.extensions.window-list show-on-all-monitors "true"

# Dash-to-Panel full current settings snapshot.
apply_dash_to_panel_settings

# Default file manager associations.
xdg-mime default org.gnome.Nautilus.desktop inode/directory
xdg-mime default org.gnome.Nautilus.desktop application/x-gnome-saved-search

echo "Done."
echo "If any setting does not apply immediately, log out and back in."
