#!/usr/bin/env bash
set -euo pipefail

MODULE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$MODULE_DIR/.." && pwd)"
source "$REPO_DIR/_common/log.sh"
init_logger_for_source "${BASH_SOURCE[0]}" "gnome-backup"
BACKUP_DIR="$MODULE_DIR/backups"
BACKUP_PATHSPEC="gnome/backups"
EXT_SRC="${XDG_DATA_HOME:-$HOME/.local/share}/gnome-shell/extensions"
QUIET=false
NO_COMMIT=false

usage() {
  cat <<USAGE
Usage: $0 [--no-commit] [--quiet]

Captures current GNOME configuration and extension inventory into gnome/backups.
Commits backup changes unless --no-commit is provided.
USAGE
}

note() {
  [[ "$QUIET" == false ]] && log "$*"
}

sanitize_field() {
  printf '%s' "$1" | tr '\n' ' ' | sed -E 's/[[:space:]]+/ /g; s/^ //; s/ $//; s/\|/%7C/g'
}

extract_info_value() {
  local file="$1"
  local key="$2"
  sed -n "s/^${key}[[:space:]]*:[[:space:]]*//p" "$file" | head -n1
}

extract_metadata_value() {
  local file="$1"
  local key="$2"
  if [[ ! -f "$file" ]]; then
    return 0
  fi
  sed -n "s/.*\"${key}\"[[:space:]]*:[[:space:]]*\"\\([^\"]*\\)\".*/\\1/p" "$file" | head -n1
}

capture_system_extensions() {
  local list_file details_file
  list_file="$BACKUP_DIR/extensions-system-list.txt"
  details_file="$BACKUP_DIR/extensions-system-details.txt"

  : > "$list_file"
  : > "$details_file"

  for root in /usr/share/gnome-shell/extensions /usr/local/share/gnome-shell/extensions /var/lib/gnome-shell/extensions; do
    [[ -d "$root" ]] || continue
    for ext_dir in "$root"/*; do
      [[ -d "$ext_dir" ]] || continue
      local uuid metadata pkg
      uuid="$(basename "$ext_dir")"
      metadata="$ext_dir/metadata.json"
      pkg="unknown"

      if command -v dpkg-query >/dev/null 2>&1; then
        pkg="$(dpkg-query -S "$metadata" 2>/dev/null | head -n1 | cut -d: -f1 || true)"
        if [[ -z "$pkg" ]]; then
          pkg="$(dpkg-query -S "$ext_dir" 2>/dev/null | head -n1 | cut -d: -f1 || true)"
        fi
        [[ -n "$pkg" ]] || pkg="unknown"
      elif command -v rpm >/dev/null 2>&1; then
        pkg="$(rpm -qf "$metadata" 2>/dev/null || true)"
        if [[ -z "$pkg" ]]; then
          pkg="$(rpm -qf "$ext_dir" 2>/dev/null || true)"
        fi
        [[ -n "$pkg" ]] || pkg="unknown"
      elif command -v pacman >/dev/null 2>&1; then
        pkg="$(pacman -Qo "$metadata" 2>/dev/null | awk '{print $5}' || true)"
        if [[ -z "$pkg" ]]; then
          pkg="$(pacman -Qo "$ext_dir" 2>/dev/null | awk '{print $5}' || true)"
        fi
        [[ -n "$pkg" ]] || pkg="unknown"
      fi

      printf '%s|%s|%s\n' "$uuid" "$root" "$pkg" >> "$list_file"
      {
        echo "[$uuid]"
        echo "source=$root"
        echo "package=$pkg"
        if [[ -f "$metadata" ]]; then
          grep -E '"(name|description|uuid|version|shell-version)"' "$metadata" || true
        fi
        echo
      } >> "$details_file"
    done
  done
}

build_manifest() {
  local manifest_file enabled_file
  manifest_file="$BACKUP_DIR/extensions-manifest.txt"
  enabled_file="$BACKUP_DIR/.extensions-enabled.tmp"

  : > "$manifest_file"
  if command -v gnome-extensions >/dev/null 2>&1; then
    gnome-extensions list --enabled 2>/dev/null | sort > "$enabled_file" || : > "$enabled_file"
  else
    : > "$enabled_file"
  fi

  {
    echo "# Generated by gnome/backup.sh on $(date +'%Y-%m-%d %H:%M:%S %Z')"
    echo "# format: uuid|scope|enabled|source_type|source|name|version"
  } > "$manifest_file"

  while IFS= read -r uuid; do
    [[ -n "$uuid" ]] || continue

    local scope enabled source_type source name version info_file system_line pkg url metadata_file metadata_root
    scope="unknown"
    enabled="false"
    source_type="manual"
    source=""
    name=""
    version=""

    if grep -Fxq "$uuid" "$enabled_file"; then
      enabled="true"
    fi

    system_line="$(grep -m1 "^${uuid}|" "$BACKUP_DIR/extensions-system-list.txt" || true)"
    if [[ -n "$system_line" ]]; then
      scope="system"
      pkg="$(printf '%s' "$system_line" | cut -d'|' -f3)"
      if [[ -n "$pkg" && "$pkg" != "unknown" ]]; then
        source_type="package"
        source="$pkg"
      fi
    elif [[ -f "$BACKUP_DIR/extensions-local-list.txt" ]] && grep -Fxq "$uuid" "$BACKUP_DIR/extensions-local-list.txt"; then
      scope="local"
    else
      scope="local"
    fi

    info_file="$BACKUP_DIR/.extension-info-${uuid//[^a-zA-Z0-9_.@-]/_}.tmp"
    if command -v gnome-extensions >/dev/null 2>&1; then
      gnome-extensions info "$uuid" > "$info_file" 2>/dev/null || : > "$info_file"
    else
      : > "$info_file"
    fi

    name="$(extract_info_value "$info_file" "Name")"
    version="$(extract_info_value "$info_file" "Version")"
    url="$(extract_info_value "$info_file" "URL")"

    metadata_file=""
    if [[ "$scope" == "local" && -f "$EXT_SRC/$uuid/metadata.json" ]]; then
      metadata_file="$EXT_SRC/$uuid/metadata.json"
    elif [[ "$scope" == "system" && -n "$system_line" ]]; then
      metadata_root="$(printf '%s' "$system_line" | cut -d'|' -f2)"
      if [[ -f "$metadata_root/$uuid/metadata.json" ]]; then
        metadata_file="$metadata_root/$uuid/metadata.json"
      fi
    fi

    if [[ -z "$name" ]]; then
      name="$(extract_metadata_value "$metadata_file" "name")"
    fi
    if [[ -z "$version" ]]; then
      version="$(extract_metadata_value "$metadata_file" "version")"
    fi
    if [[ -z "$url" ]]; then
      url="$(extract_metadata_value "$metadata_file" "url")"
    fi

    if [[ "$scope" == "local" ]]; then
      if [[ "$url" == *"extensions.gnome.org"* ]]; then
        source_type="ego"
        source="$url"
      elif [[ "$url" == *.zip || "$url" == *.zip\?* ]]; then
        source_type="url"
        source="$url"
      elif [[ -n "$url" ]]; then
        source_type="manual"
        source="$url"
      fi
    fi

    printf '%s|%s|%s|%s|%s|%s|%s\n' \
      "$(sanitize_field "$uuid")" \
      "$(sanitize_field "$scope")" \
      "$(sanitize_field "$enabled")" \
      "$(sanitize_field "$source_type")" \
      "$(sanitize_field "$source")" \
      "$(sanitize_field "$name")" \
      "$(sanitize_field "$version")" >> "$manifest_file"

    rm -f "$info_file"
  done < "$BACKUP_DIR/extensions-list.txt"

  rm -f "$enabled_file"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-commit)
      NO_COMMIT=true
      ;;
    --quiet)
      QUIET=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n' "$1" >&2
      usage >&2
      exit 1
      ;;
  esac
  shift
done

for cmd in dconf git; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    printf 'error: required command not found: %s\n' "$cmd" >&2
    exit 1
  fi
done

mkdir -p "$BACKUP_DIR"

note "Dumping dconf trees"
dconf dump /org/gnome/ > "$BACKUP_DIR/dconf-org-gnome.ini"
dconf dump /org/gtk/ > "$BACKUP_DIR/dconf-org-gtk.ini"

if command -v gnome-extensions >/dev/null 2>&1; then
  note "Recording extension inventory"
  gnome-extensions list | sort > "$BACKUP_DIR/extensions-list.txt"
  : > "$BACKUP_DIR/extensions-info.txt"
  while IFS= read -r uuid; do
    [[ -z "$uuid" ]] && continue
    {
      echo "[$uuid]"
      gnome-extensions info "$uuid" || true
      echo
    } >> "$BACKUP_DIR/extensions-info.txt"
  done < "$BACKUP_DIR/extensions-list.txt"
else
  note "gnome-extensions command missing; writing empty inventory"
  : > "$BACKUP_DIR/extensions-list.txt"
  : > "$BACKUP_DIR/extensions-info.txt"
fi

if [[ -d "$EXT_SRC" ]]; then
  note "Recording local extension inventory"
  find "$EXT_SRC" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort > "$BACKUP_DIR/extensions-local-list.txt"
else
  note "No local extension directory found at $EXT_SRC"
  : > "$BACKUP_DIR/extensions-local-list.txt"
fi

# Legacy cleanup: older versions stored full extension source trees.
rm -rf "$BACKUP_DIR/local-extensions"

note "Recording system extension inventory"
capture_system_extensions

note "Building extension install manifest"
build_manifest

if [[ -f "$HOME/.config/mimeapps.list" ]]; then
  cp "$HOME/.config/mimeapps.list" "$BACKUP_DIR/mimeapps.list"
else
  : > "$BACKUP_DIR/mimeapps.list"
fi

if [[ "$NO_COMMIT" == true ]]; then
  note "Backup updated without commit (--no-commit)"
  exit 0
fi

note "Checking for changes"
cd "$REPO_DIR"
git add -- "$BACKUP_PATHSPEC"

if git diff --cached --quiet -- "$BACKUP_PATHSPEC"; then
  note "No changes to commit"
  exit 0
fi

msg="chore(gnome-backup): snapshot $(date +'%Y-%m-%d %H:%M:%S %Z')"
note "Committing snapshot"
git commit -m "$msg" -- "$BACKUP_PATHSPEC"
note "Committed: $msg"
