[Unit]
After=bluetooth.target systemd-udev-settle.service
Wants=bluetooth.target systemd-udev-settle.service

[Service]
ExecStartPre=
ExecStartPre=/usr/bin/udevadm settle --timeout=15
ExecStartPre=/usr/bin/sleep 6
Restart=always
RestartSec=2
